export const VALORANT_MAPS = ["Lotus", "Ascent", "Bind", "Haven", "Split", "Breeze", "Sunset", "Abyss"] as const;
export type MapVetoPhase = "team_a_ban" | "team_b_ban" | "team_a_pick" | "team_b_pick" | "completed";
export type MapVetoAction = { type: "ban" | "pick"; mapId: string };
export type MapVetoRole = "admin" | "captain_a" | "captain_b" | "caster" | "viewer";
export type MapVetoMap = { id: string; status: "available" | "banned" | "picked" | "decider"; by?: "team_a" | "team_b" };
export interface MapVetoState { format: "BO3"; phase: MapVetoPhase; status: "active" | "completed"; activeTeam: "team_a" | "team_b" | null; maps: MapVetoMap[]; turnStartedAt: string; turnDuration: number; history: Array<MapVetoAction & { team: "team_a" | "team_b"; at: string }>; }
const PHASE_TEAM: Record<Exclude<MapVetoPhase, "completed">, "team_a" | "team_b"> = { team_a_ban: "team_a", team_b_ban: "team_b", team_a_pick: "team_a", team_b_pick: "team_b" };
export function createInitialMapVetoState(maps: readonly string[] = VALORANT_MAPS, turnDuration = 30, now = new Date().toISOString()): MapVetoState { if (maps.length < 5) throw new Error("BO3 map veto requires at least 5 maps"); return { format: "BO3", phase: "team_a_ban", status: "active", activeTeam: "team_a", maps: maps.map((id) => ({ id, status: "available" })), turnStartedAt: now, turnDuration, history: [] }; }
export function canSubmitAction(state: MapVetoState, action: MapVetoAction, role: MapVetoRole): boolean { if (state.status !== "active" || state.phase === "completed") return false; const team = PHASE_TEAM[state.phase]; const expectedRole = team === "team_a" ? "captain_a" : "captain_b"; return (role === "admin" || role === expectedRole) && action.type === (state.phase.endsWith("ban") ? "ban" : "pick") && state.maps.some((map) => map.id === action.mapId && map.status === "available"); }
export function applyMapVetoAction(state: MapVetoState, action: MapVetoAction, role: MapVetoRole, now = new Date().toISOString()): MapVetoState { if (!canSubmitAction(state, action, role)) throw new Error("Invalid map veto action"); const team = PHASE_TEAM[state.phase]; const maps = state.maps.map((map) => map.id === action.mapId ? { ...map, status: action.type === "ban" ? "banned" as const : "picked" as const, by: team } : map); const nextPhase: MapVetoPhase = state.phase === "team_a_ban" ? "team_b_ban" : state.phase === "team_b_ban" ? "team_a_pick" : state.phase === "team_a_pick" ? "team_b_pick" : "completed"; const completed = nextPhase === "completed"; return { ...state, phase: nextPhase, status: completed ? "completed" : "active", activeTeam: completed ? null : PHASE_TEAM[nextPhase], maps: completed ? maps.map((map) => map.status === "available" ? { ...map, status: "decider" as const } : map) : maps, turnStartedAt: now, history: [...state.history, { ...action, team, at: now }] }; }
export function getDeciderMap(state: MapVetoState): MapVetoMap | undefined { return state.maps.find((map) => map.status === "decider"); }
