create table if not exists public.draft_sessions (id uuid primary key default gen_random_uuid(), room_id uuid not null references public.rooms(id) on delete cascade, mode text not null default 'valorant_map_veto', format text not null default 'BO3', state jsonb not null, status text not null default 'active', version bigint not null default 0, turn_deadline timestamptz, created_at timestamptz not null default now(), unique(room_id, mode));
create table if not exists public.draft_actions (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.draft_sessions(id) on delete cascade, sequence_no bigint not null, actor_id uuid references auth.users(id), actor_role text not null, action jsonb not null, created_at timestamptz not null default now(), unique(session_id, sequence_no));
create table if not exists public.overlay_tokens (id uuid primary key default gen_random_uuid(), room_id uuid not null references public.rooms(id) on delete cascade, token_hash text not null unique, label text not null, created_at timestamptz not null default now());
alter table public.draft_sessions enable row level security; alter table public.draft_actions enable row level security; alter table public.overlay_tokens enable row level security;
create policy "Draft sessions readable" on public.draft_sessions for select using (true);
create policy "Draft sessions room creator writes" on public.draft_sessions for all to authenticated using (exists (select 1 from public.rooms r where r.id = room_id and r.created_by = (select auth.uid()))) with check (exists (select 1 from public.rooms r where r.id = room_id and r.created_by = (select auth.uid())));
create policy "Draft actions readable" on public.draft_actions for select using (true);
create policy "Overlay tokens readable by room creator" on public.overlay_tokens for select to authenticated using (exists (select 1 from public.rooms r where r.id = room_id and r.created_by = (select auth.uid())));
create index if not exists draft_sessions_room_id_idx on public.draft_sessions(room_id); create index if not exists draft_actions_session_seq_idx on public.draft_actions(session_id, sequence_no); create index if not exists overlay_tokens_hash_idx on public.overlay_tokens(token_hash);
